"""ExplanationComposerGraph — LangGraph workflow (DERCAS 13.1.4).

GatherEvidence → DetectConflicts → DraftExplanation →
ValidateClaimsGuardrails → PublishReport → Finalize
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

import httpx
from langgraph.graph import StateGraph, END

from langgraph_workflows.state import GraphState, update_exec
from langgraph_workflows.tools.storage import get_storage_tool

logger = logging.getLogger(__name__)

INFERENCE_SERVICE_URL = os.getenv("INFERENCE_SERVICE_URL", "http://localhost:8003")
EHR_SERVICE_URL = os.getenv("EHR_SERVICE_URL", "http://localhost:8004")
GRAPH_SERVICE_URL = os.getenv("GRAPH_SERVICE_URL", "http://localhost:8005")

# Clinical guardrails — prohibited phrases (DERCAS 14.2)
PROHIBITED_PHRASES = [
    "definitive diagnosis",
    "confirmed diagnosis",
    "this patient has",
    "diagnostic certainty",
    "conclusive evidence that",
    "we can confirm",
    "definite presence of",
    "the patient is diagnosed with",
]

# Required disclaimer
DISCLAIMER = (
    "DISCLAIMER: This analysis is generated by an AI-assisted research system. "
    "Results are based on morphological pattern aggregation and computational models (THESIS_INTERNAL evidence). "
    "This is NOT a clinical diagnosis. All findings must be confirmed with standard molecular testing "
    "and pathologist review. Intended use: research / decision support (non-diagnostic)."
)


async def gather_evidence(state: GraphState) -> GraphState:
    """Gather all evidence from inference results, EHR, and graph."""
    state = update_exec(state, status="running", progress=0.1, current_node="gather_evidence")
    ctx = state.get("context", {})
    inputs = state.get("inputs", {})
    inter = dict(state.get("_intermediate", {}))

    evidence: dict[str, Any] = {
        "case_id": ctx.get("case_id"),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "patterns": [],
        "mutations": [],
        "ehr_entities": [],
        "graph_nodes": [],
    }

    # Gather pattern results from state outputs (set by ImageAnalysisGraph)
    outputs = state.get("outputs", {})
    evidence["patterns"] = outputs.get("pattern_outputs", [])
    evidence["mutations"] = outputs.get("genetic_outputs", [])

    # Try fetching latest inference results if not already in state
    if not evidence["patterns"]:
        image_id = inputs.get("image_id")
        if image_id:
            try:
                async with httpx.AsyncClient(base_url=INFERENCE_SERVICE_URL, timeout=10.0) as client:
                    resp = await client.get(f"/api/v1/images/{image_id}/results/latest")
                    if resp.status_code == 200:
                        result = resp.json()
                        evidence["patterns"] = result.get("pattern_results", [])
                        evidence["mutations"] = result.get("genetic_results", [])
            except Exception as exc:
                logger.debug("Could not fetch inference results: %s", exc)

    # Gather EHR entities
    ehr_id = inputs.get("ehr_id")
    if ehr_id:
        try:
            async with httpx.AsyncClient(base_url=EHR_SERVICE_URL, timeout=10.0) as client:
                resp = await client.get(f"/api/v1/ehr/{ehr_id}/entities")
                if resp.status_code == 200:
                    evidence["ehr_entities"] = resp.json()
        except Exception as exc:
            logger.debug("Could not fetch EHR entities: %s", exc)

    inter["evidence"] = evidence
    state["_intermediate"] = inter
    return state


async def detect_conflicts(state: GraphState) -> GraphState:
    """Detect conflicts between different evidence sources."""
    state = update_exec(state, progress=0.3, current_node="detect_conflicts")
    inter = dict(state.get("_intermediate", {}))
    evidence = inter.get("evidence", {})
    conflicts: list[dict[str, str]] = []

    patterns = evidence.get("patterns", [])
    mutations = evidence.get("mutations", [])

    # Check for contradictions between mutation predictions and patterns
    # EGFR is associated with lepidic/papillary, KRAS with solid/cribriform
    egfr = next((m for m in mutations if m.get("mutation") == "EGFR"), None)
    kras = next((m for m in mutations if m.get("mutation") == "KRAS"), None)

    if egfr and kras and egfr.get("status") == "POS" and kras.get("status") == "POS":
        conflicts.append({
            "type": "MUTUAL_EXCLUSION",
            "detail": "EGFR and KRAS mutations are typically mutually exclusive in lung adenocarcinoma. "
                      "Both are predicted as positive. Molecular testing is strongly recommended.",
        })

    # Check for inconclusive results
    inconclusive = [m for m in mutations if m.get("status") == "INCONCLUSIVE"]
    if inconclusive:
        conflicts.append({
            "type": "INCONCLUSIVE_RESULTS",
            "detail": f"{len(inconclusive)} mutation prediction(s) are inconclusive: "
                      f"{', '.join(m['mutation'] for m in inconclusive)}. "
                      "Consider additional testing.",
        })

    # Check if predominant pattern has low confidence
    if patterns:
        top = max(patterns, key=lambda p: p.get("percentage", 0))
        if top.get("score", 0) < 0.5:
            conflicts.append({
                "type": "LOW_CONFIDENCE",
                "detail": f"Predominant pattern '{top.get('pattern')}' has low confidence "
                          f"(score={top.get('score', 0):.2f}). Review recommended.",
            })

    inter["conflicts"] = conflicts
    state["_intermediate"] = inter
    return state


async def draft_explanation(state: GraphState) -> GraphState:
    """Generate a structured explanation report from gathered evidence."""
    state = update_exec(state, progress=0.5, current_node="draft_explanation")
    inter = dict(state.get("_intermediate", {}))
    evidence = inter.get("evidence", {})
    conflicts = inter.get("conflicts", [])

    patterns = evidence.get("patterns", [])
    mutations = evidence.get("mutations", [])

    # Build structured explanation
    sections: list[str] = []

    # Header
    sections.append("# Morphological and Molecular Analysis Report")
    sections.append(f"\n**Case ID:** {evidence.get('case_id', 'N/A')}")
    sections.append(f"**Generated:** {evidence.get('timestamp', 'N/A')}")
    sections.append(f"**Evidence Source:** THESIS_INTERNAL")

    # Pattern analysis
    sections.append("\n## Histological Pattern Analysis")
    if patterns:
        predominant = max(patterns, key=lambda p: p.get("percentage", 0))
        sections.append(f"\n**Predominant pattern:** {predominant.get('pattern', 'N/A')} "
                       f"({predominant.get('percentage', 0):.1f}%)")
        sections.append("\n| Pattern | Percentage | Score | Conclusive |")
        sections.append("|---------|-----------|-------|------------|")
        for p in sorted(patterns, key=lambda x: x.get("percentage", 0), reverse=True):
            sections.append(
                f"| {p.get('pattern', '')} | {p.get('percentage', 0):.1f}% | "
                f"{p.get('score', 0):.2f} | {'Yes' if p.get('is_conclusive') else 'No'} |"
            )
    else:
        sections.append("\nNo pattern analysis available.")

    # Mutation predictions
    sections.append("\n## Mutation Prediction (Morphology-Based)")
    if mutations:
        sections.append("\n| Gene | Score | Status | Evidence |")
        sections.append("|------|-------|--------|----------|")
        for m in mutations:
            sections.append(
                f"| {m.get('mutation', '')} | {m.get('score', 0):.2f} | "
                f"{m.get('status', '')} | {m.get('evidence_source', 'THESIS_INTERNAL')} |"
            )
        sections.append("\n*Note: Mutation predictions are based on morphological features and "
                       "XGBoost modeling. They are NOT equivalent to molecular testing.*")
    else:
        sections.append("\nNo mutation predictions available.")

    # Conflicts
    if conflicts:
        sections.append("\n## Alerts and Conflicts")
        for c in conflicts:
            sections.append(f"\n**{c['type']}:** {c['detail']}")

    # EHR entities
    ehr_entities = evidence.get("ehr_entities", [])
    if ehr_entities:
        sections.append("\n## EHR Entity Extractions")
        sections.append("\n| Entity | Type | Confidence |")
        sections.append("|--------|------|------------|")
        for e in ehr_entities:
            sections.append(f"| {e.get('text', '')} | {e.get('entity_type', '')} | {e.get('confidence', 0):.2f} |")

    # Disclaimer
    sections.append(f"\n---\n\n{DISCLAIMER}")

    draft = "\n".join(sections)
    inter["draft"] = draft
    state["_intermediate"] = inter
    return state


async def validate_claims_guardrails(state: GraphState) -> GraphState:
    """Validate that the draft does not contain prohibited clinical claims."""
    state = update_exec(state, progress=0.7, current_node="validate_claims_guardrails")
    inter = dict(state.get("_intermediate", {}))
    draft = inter.get("draft", "")

    violations = [ph for ph in PROHIBITED_PHRASES if ph.lower() in draft.lower()]
    inter["guardrails_passed"] = len(violations) == 0
    inter["violations"] = violations

    if violations:
        logger.warning("Guardrail violations detected: %s", violations)
        # Auto-fix: redact prohibited phrases
        fixed_draft = draft
        for v in violations:
            import re
            fixed_draft = re.sub(
                re.escape(v), "[REDACTED — prohibited clinical claim]", fixed_draft, flags=re.IGNORECASE
            )
        inter["draft"] = fixed_draft
        inter["auto_redacted"] = True

    state["_intermediate"] = inter
    return state


async def publish_report(state: GraphState) -> GraphState:
    """Publish the explanation report to storage."""
    state = update_exec(state, progress=0.9, current_node="publish_report")
    inter = dict(state.get("_intermediate", {}))
    outputs = dict(state.get("outputs", {}))

    report_id = str(uuid4())
    draft = inter.get("draft", "No report generated.")

    # Upload report to MinIO
    storage = get_storage_tool()
    report_bytes = draft.encode("utf-8")
    report_key = f"reports/{report_id}.md"
    report_uri = storage.upload_file(report_key, report_bytes, "text/markdown")

    # Also upload as HTML
    html_content = _markdown_to_html(draft)
    html_key = f"reports/{report_id}.html"
    storage.upload_file(html_key, html_content.encode("utf-8"), "text/html")

    outputs["report_id"] = report_id
    outputs["report_uri"] = report_uri
    state["outputs"] = outputs
    return state


async def finalize(state: GraphState) -> GraphState:
    """Mark workflow as completed."""
    state["execution"] = {
        **state.get("execution", {}),
        "status": "completed",
        "progress": 1.0,
        "current_node": "finalize",
    }
    return state


def _markdown_to_html(md: str) -> str:
    """Simple markdown-to-HTML conversion for reports."""
    lines = md.split("\n")
    html_parts = [
        "<!DOCTYPE html><html><head><meta charset='utf-8'>",
        "<title>Explanation Report</title>",
        "<style>body{font-family:system-ui;max-width:800px;margin:0 auto;padding:20px;}"
        "table{border-collapse:collapse;width:100%;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}"
        "th{background:#f5f5f5;}.disclaimer{background:#fff3cd;border:1px solid #ffc107;padding:12px;border-radius:4px;margin-top:20px;}</style>",
        "</head><body>",
    ]

    for line in lines:
        if line.startswith("# "):
            html_parts.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            html_parts.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("**") and line.endswith("**"):
            html_parts.append(f"<p><strong>{line[2:-2]}</strong></p>")
        elif line.startswith("|"):
            # Table row
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if all(c.startswith("-") for c in cells):
                continue
            if line.startswith("| Pattern") or line.startswith("| Gene") or line.startswith("| Entity"):
                html_parts.append("<table><tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
            else:
                html_parts.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
        elif "DISCLAIMER" in line:
            html_parts.append(f"<div class='disclaimer'>{line}</div>")
        elif line.strip():
            html_parts.append(f"<p>{line}</p>")

    html_parts.append("</body></html>")
    return "\n".join(html_parts)


def create_explanation_composer_graph():
    """Build and compile the ExplanationComposerGraph."""
    wf = StateGraph(GraphState)
    for name, fn in [
        ("gather_evidence", gather_evidence),
        ("detect_conflicts", detect_conflicts),
        ("draft_explanation", draft_explanation),
        ("validate_claims_guardrails", validate_claims_guardrails),
        ("publish_report", publish_report),
        ("finalize", finalize),
    ]:
        wf.add_node(name, fn)

    wf.set_entry_point("gather_evidence")
    wf.add_edge("gather_evidence", "detect_conflicts")
    wf.add_edge("detect_conflicts", "draft_explanation")
    wf.add_edge("draft_explanation", "validate_claims_guardrails")
    wf.add_edge("validate_claims_guardrails", "publish_report")
    wf.add_edge("publish_report", "finalize")
    wf.add_edge("finalize", END)
    return wf.compile()
